### ISSUE TITLE
-bash: /pia-wg-config: No such file or directory

### ISSUE THREAD

**Issue by daNutzzzzz** [kylegrantlucas/pia-wg-config#2]
Hi, i installed go and then ran `pia-wg-config -o wg0.conf USERNAME PASSWORD` but i get the error: `-bash: /pia-wg-config: No such file or directory`

**OS Ubuntu 22.04**

**Comment by brichardson2x** [comment]
Don't know if you still need it, but for anyone else.

Not sure who you installed it with, but I installed it with sudo as the non-root.

It installs at your local directory here: ~/go/bin/pia-wg-config

So I did this to move that command to the correct bin folder.
Assuming you're using a non-root

`sudo cp ~/go/bin/pia-wg-config /usr/bin/pia-wg-config`

And you should be able to run it then.
